name: Create GitHub Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: ./.github/workflows/npm-release.yml
    with:
      node-version: 18
      require-build: true
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}